[package]
name = "libretakt"
version = "0.1.0"
edition = "2021"
default-run = "client"

# Required to use library in the `examples` folder
[lib]
bench = false

[profile.dev]
opt-level = 3               # Use slightly better optimizations.
overflow-checks = false     # Disable integer overflow checks.
lto = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rodio = { version = "0.15", default-features = true }
macroquad = { version = "0.3", default-features = false }
synfx-dsp = "0.5.4"
serde_json = "1.0.86"
serde = { version = "1.0", features = ["derive"] }
flume = "0.10.14"
actix-web="3.2.0" # duh
actix-web-actors="3" # actors specific to web
actix = "0.10.0" # actors
uuid = { version = "0.8", features = ["v4", "serde"] } # uuid's fit well in this context.
flexbuffers = "2.0.0"
serde_derive = "1.0.147"
env_logger = "0.9.1"
log = "0.4.17"
num = "0.4"
num-derive = "0.3"
num-traits = "0.2"
strum = "0.24"
strum_macros = "0.24"
tungstenite = "0.18.0"
url = "2.3.1"
futures-util = "0.3"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }

[[bin]]
bench = false
path = "src/main.rs"
name = "client"

[[bin]]
bench = false
path = "src/web_sockets/main_server.rs"
name = "ws_server"

[[bin]]
bench = false
path = "src/web_sockets/main_client.rs"
name = "ws_client"
