[package]
name = "libretakt"
version = "0.1.0"
edition = "2021"
default-run = "client"
# Required to use library in the `examples` folder
[lib]
bench = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rodio = { version = "0.15", default-features = true }
macroquad = { version = "0.3", default-features = false }
synfx-dsp = "0.5.4"
serde_json = "1.0.86"
serde = { version = "1.0", features = ["derive"] }
flume = "0.10.14"
actix-web = { version = "4.0.0-beta.10" }
actix-web-actors="3"
actix = "0.10.0"
uuid = { version = "0.8", features = ["v4", "serde"] }
awc = "3.0.1"

[[bin]]
bench = false
path = "src/main.rs"
name = "client"

[[bin]]
bench = false
path = "src/web_sockets/main_server.rs"
name = "ws_server"

[[bin]]
bench = false
path = "src/web_sockets/main_client.rs"
name = "ws_client"
