[package]
name = "libretakt"
version = "0.1.0"
edition = "2021"

# Required to use library in the `examples` folder
[lib]
bench = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rodio = { version = "0.15", default-features = true }
macroquad = { version = "0.3", default-features = false }
synfx-dsp = "0.5.4"
actix-web="3.2.0" 
actix-web-actors="3"
actix = "0.10.0"
uuid = { version = "0.8", features = ["v4", "serde"] }
