[package]
name = "libretakt"
version = "0.1.0"
edition = "2021"
default-run = "client"

# Required to use library in the `examples` folder
[lib]
bench = false

[profile.dev]
opt-level = 3
overflow-checks = false
lto = true

[workspace]
members = ["mverb", "server"]
# default-members = ["mverb"]

[dependencies]
mverb = {path = "mverb" }
server = {path = "server" }

rodio = { version = "0.15", default-features = true }
macroquad = { version = "0.3", default-features = false }
synfx-dsp = "0.5.4"
serde_json = "1.0.86"
serde = { version = "1.0", features = ["derive"] }
flume = "0.10.14"
flexbuffers = "2.0.0"
serde_derive = "1.0.147"
env_logger = "0.9.1"
log = "0.4.17"
num = "0.4"
num-derive = "0.3"
num-traits = "0.2"
strum = "0.24"
strum_macros = "0.24"

[[bin]]
bench = false
path = "src/main.rs"
name = "client"


