[package]
name = "libretakt"
version = "0.1.0"
edition = "2021"
default-run = "client"

# Required to use library in the `examples` folder
[lib]
bench = false

[profile.dev]
opt-level = 3
overflow-checks = false

[profile.release]
lto = true

[workspace]
members = ["mverb", "common"]

[workspace.dependencies]
common = { path = "common" }
uuid = { version = "0.8", features = ["v4", "serde"] } # uuid's fit well in this context.
url = "2.3.1"
futures-channel = "0.3.25"
tokio = { version = "1.8.4", features = ["full"] }
futures-util = "0.3"
log = "0.4.17"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
env_logger = "0.11.3"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
mverb = {path = "mverb" }
common = { path = "common" }
url = {workspace = true}
futures-util = {workspace = true}
tokio = {workspace = true}
log = {workspace=true}
futures = "0.3.25"

rodio = { version = "0.17", default-features = true }
macroquad = { version = "0.3", default-features = false }
serde_json = "1.0.86"
flume = "0.10.14"
serde_derive = "1.0.147"
tokio-tungstenite = "0.18.0"
num = "0.4"
num-derive = "0.3"
num-traits = "0.2"
strum = "0.24"
strum_macros = "0.24"

# For cargo-fuzz
arbitrary = { version = "1", features = ["derive"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen-futures = "0.4"
egui = "0.27.0"
eframe = { version = "0.27.0", default-features = false, features = [
    "accesskit",     # Make egui comptaible with screen readers. NOTE: adds a lot of dependencies.
    "default_fonts", # Embed the default egui fonts.
    "glow",          # Use the glow rendering backend. Alternative: "wgpu".
    "persistence",   # Enable restoring app state when restarting the app.
] }
log = "0.4"
reqwasm = "0.5.0"
ewebsock = "0.5.0"

[[bin]]
bench = false
path = "src/main.rs"
name = "client"

