name: Rust CI
on: [push]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          cargo fmt --check

  build-server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          sudo apt install libasound2-dev
          cargo build --release --all-targets --all-features --examples --workspace

  deploy-wasm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: setup toolchain
        run: rustup target add wasm32-unknown-unknown
      - name: Build
        run: |
          wget -qO- https://github.com/thedodd/trunk/releases/download/v0.17.1/trunk-x86_64-unknown-linux-gnu.tar.gz | tar -xzf-
          TRUNK_BUILD_PUBLIC_URL="https://wint3rmute.github.io/libretakt/" ./trunk build --release
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: 'dist'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1

  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          sudo apt install libasound2-dev
          cargo clippy --all-targets --all-features --examples --workspace

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          sudo apt install libasound2-dev
          cargo test --workspace

  rust_docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and push Docker images
        uses: docker/build-push-action@v3.2.0
